### ISSUE TITLE
Has there ever been a time when a reboot has failed?

### ISSUE THREAD

**Issue by vlad-at-work** [playsignage/cordova-plugin-reboot#1]
Thanks for this nifty plugin!
I was just checking out the Java class and there's a clause there in case the reboot fails.

Does this actually ever happen though? I imagine `sudo reboot` will work nicely 100% of the time.

Just confirming this as it's very important that this plugin works.

**Comment by reederz** [comment]
@vladdypwnz sorry for the late reply. No, we haven't experienced this failing.

**Comment by reederz** [comment]
I'm gonna close this issue now.
